# SPDX-FileCopyrightText: 2020 Serokell <https://serokell.io>
#
# SPDX-License-Identifier: MPL-2.0

* nix-pandoc

A wrapper around =mkDerivation= to build Pandoc documents with Nix

** Basic usage
Put the following into your =flake.nix=:

#+BEGIN_SRC nix
  {
    inputs = {
      nix-pandoc.url = "github:serokell/nix-pandoc";
      nix-pandoc.inputs.nixpkgs.follows = "nixpkgs";
    };
    outputs = { self, nixpkgs, nix-pandoc }: {
      defaultPackage = builtins.mapAttrs (system: pkgs: nix-pandoc.mkDoc.${system} {
        name = "your-document-name";
        src = ./.;
        phases = [ "unpackPhase" "buildPhase" "installPhase" ];
        buildPhase = "pandoc --pdf-engine=xelatex -o $name.pdf ./your-document.md";
        installPhase = "mkdir -p $out; cp $name.pdf $out";
      }) nixpkgs.legacyPackages;
    };
  }
#+END_SRC

You may also want to place a Makefile in the root of your project that
would contain instructions on how to build and install the files. If you do that, you can now do

#+BEGIN_SRC nix
  {
    inputs = {
      nix-pandoc.url = "github:serokell/nix-pandoc";
      nix-pandoc.inputs.nixpkgs.follows = "nixpkgs";
    };
    outputs = { self, nixpkgs, nix-pandoc }: {
      defaultPackage = builtins.mapAttrs (system: pkgs: nix-pandoc.mkDoc.${system} {
        name = "your-document-name";
        src = ./.;
      }) nixpkgs.legacyPackages;
    };
  }
#+END_SRC

You can run =nix build= to build your documents, or =nix develop= to get
into a shell from where you can run =make= to build your documents more
granularly.

** Fonts
Pass a =font= argument to =mkDoc= containing the path to your font's package
(the font(s) must be located under =share/fonts/=).

** More Texlive packages
You may build your own texlive distribution with =texlive.combined= and pass
it to =mkDoc= as =texlive-combined=.

** Extra TEX inputs
You may pass =extraTexInputs=, which should be a list of directories containing
=sty= files that you may later use in your document.

** Fork extensions
This fork (maintained by Marc Zander, =m4rc2a/nix-pandoc=) adds two helpers
that are handy when repeatedly writing papers:

*** =mkShell= – reusable development shell
Builds a =devShell= with =make=, =pandoc=, =texlive= (xelatex, tikz, ...) and
=poppler-utils= (=pdfinfo=, =pdftotext=, =pdftoppm=) so you can build and
inspect PDFs directly. From a project flake:

#+BEGIN_SRC nix
  devShells = { default = nix-pandoc.mkShell.${system} { }; };
#+END_SRC

Options: =texlive-combined= (default: =texlive.combined.scheme-medium=),
=extraPackages=.

*** =lib.pageCheck= – page-count check for =mkDoc=
Returns a =checkPhase= snippet that fails when the built PDF is outside a page
range. Combined with =mkDoc= (which forwards arbitrary stdenv attributes):

#+BEGIN_SRC nix
  defaultPackage = nix-pandoc.mkDoc.${system} {
    name = "your-document-name";
    src = ./.;
    extraBuildInputs = [ pkgs.poppler_utils ];
    phases = [ "unpackPhase" "buildPhase" "installPhase" "checkPhase" ];
    checkPhase = nix-pandoc.lib.pageCheck {
      file = "$out/your-document.pdf";
      min = 3;
      max = 5;
    };
  };
#+END_SRC

Then =nix flake check= (with the derivation in =checks=) verifies the page count.

** License
This project is licensed under the Mozilla Public License, version 2.0;
You may read more in [[./LICENSE]].

** About Serokell
nix-pandoc is maintained and funded with ❤ by [[https://serokell.io/][Serokell]].
The names and logo for Serokell are trademark of Serokell OÜ.

We love open source software! See [[https://serokell.io/community?utm_source=github][our
other projects]] or [[https://serokell.io/hire-us?utm_source=github][hire
us]] to design, develop and grow your idea!
